"""Lightweight utilities for exporting numeric results.

These helpers are used by analysis scripts to save CSV/JSON files (for pgfplots
or post-processing) and small LaTeX ``tabular`` snippets (for easy inclusion via
``\\input{...}``).

Design goals:
- No extra dependencies beyond NumPy + stdlib.
- Stable, LaTeX-friendly formatting (booktabs tables; escaping special chars).
- “Just write the file next to the figure” ergonomics.
"""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path

import numpy as np


def save_fig(fig, out_dir: Path, name: str, *, ext: str = "png") -> Path:
    """Save a Matplotlib figure and close it."""
    out_dir.mkdir(parents=True, exist_ok=True)
    ext = ext.lstrip(".")
    path = out_dir / f"{name}.{ext}"
    fig.savefig(path)
    try:
        import matplotlib.pyplot as plt  # local import to keep this module light

        plt.close(fig)
    except Exception:
        pass
    print(f"  wrote {path}")
    return path


def fmt(x: object) -> str:
    """Format scalars for CSV/TeX output (NaNs become empty)."""
    if x is None:
        return ""
    if isinstance(x, (np.floating, float)):
        xf = float(x)
        if np.isnan(xf):
            return ""
        if np.isinf(xf):
            return "inf" if xf > 0 else "-inf"
        return f"{xf:.10g}"
    if isinstance(x, (np.integer, int)):
        return str(int(x))
    return str(x)


def write_csv(path: Path, header: list[str], rows: list[list[object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(header)
        for row in rows:
            w.writerow([fmt(v) for v in row])
    print(f"  wrote {path}")


def jsonify(x: object):
    """Convert NumPy types to JSON-serialisable Python types."""
    if x is None:
        return None
    if isinstance(x, (np.floating, float)):
        xf = float(x)
        if np.isnan(xf):
            return None
        if np.isinf(xf):
            return "inf" if xf > 0 else "-inf"
        return xf
    if isinstance(x, (np.integer, int)):
        return int(x)
    if isinstance(x, np.ndarray):
        return [jsonify(v) for v in x.tolist()]
    if isinstance(x, dict):
        return {str(k): jsonify(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [jsonify(v) for v in x]
    return x


def write_json(path: Path, obj: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(jsonify(obj), indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  wrote {path}")


_LATEX_ESCAPE: dict[str, str] = {
    "\\": "\\textbackslash{}",
    "&": "\\&",
    "%": "\\%",
    "$": "\\$",
    "#": "\\#",
    "_": "\\_",
    "{": "\\{",
    "}": "\\}",
    "~": "\\textasciitilde{}",
    "^": "\\textasciicircum{}",
}


def tex_escape(s: object) -> str:
    text = str(s)
    return "".join(_LATEX_ESCAPE.get(ch, ch) for ch in text)


def write_tex_tabular(
    path: Path,
    header: list[str],
    rows: list[list[object]],
    *,
    generated_by: str | None = None,
) -> None:
    """Write a LaTeX tabular (no floating table wrapper).

    Requires \\usepackage{booktabs}.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    aligns = "l" + "r" * (len(header) - 1)
    lines = []
    if generated_by:
        lines.append(f"% Auto-generated by {generated_by}")
    else:
        lines.append("% Auto-generated")
    lines += [
        "% Requires: \\usepackage{booktabs}",
        f"\\begin{{tabular}}{{{aligns}}}",
        "\\toprule",
        " & ".join(tex_escape(h) for h in header) + " \\\\",
        "\\midrule",
    ]
    for row in rows:
        parts = [tex_escape(fmt(v)) for v in row]
        lines.append(" & ".join(parts) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {path}")


def slug(s: str) -> str:
    s = s.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return s.strip("_")


def write_square_matrix(
    base_path: Path,
    labels: list[str],
    matrix: np.ndarray,
    *,
    value_name: str = "cosine",
) -> None:
    """Write both a wide and long CSV for a square matrix.

    Wide: <base>.csv with row/col labels.
    Long: <base>_long.csv with (row, col, value).
    """
    wide = base_path.with_suffix(".csv")
    rows_wide: list[list[object]] = []
    for i, rlab in enumerate(labels):
        rows_wide.append([rlab] + [float(matrix[i, j]) for j in range(len(labels))])
    write_csv(wide, ["row"] + labels, rows_wide)

    long = base_path.with_name(base_path.name + "_long").with_suffix(".csv")
    rows_long: list[list[object]] = []
    for i, rlab in enumerate(labels):
        for j, clab in enumerate(labels):
            rows_long.append([rlab, clab, float(matrix[i, j])])
    write_csv(long, ["row", "col", value_name], rows_long)
